### ISSUE TITLE
Publishing from "dist" and missing package.json

### ISSUE THREAD

**Issue by appsolutegeek** [semantic-release/npm#128]
Hi,

I am trying to publish from a subdirectory named dist. I have the following plugin configured.

```
    ["@semantic-release/npm", {
      "pkgRoot": "dist",
    }],
```

I, of course, get an error about the missing package.json as it doesn't exist there. 

```
[9:13:33 AM] [semantic-release] › ✖  ENOPKG Missing `package.json` file.
A package.json file (https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.

Please follow the npm guideline (https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid package.json file.

{ AggregateError:
    SemanticReleaseError: Missing `package.json` file.
```

I tried adding a lifetime hook to force a copy first but it didn't work. This is what I tried

```
    "postversion": "cp package.json dist"
```

I am probably using the wrong lifetime hook ?

Is there a correct way to do this ?

Thanks in advance

**Comment by pvdlg** [comment]
Why are you trying to publish **from** `dist`? Shouldn't you publish the `dist` directory from the root of your project?

Typically a project with compiled files would have the following in the `package.json`:
```
{
  "files": ["dist/**"],
  "main": "dist/index.js"
}
```
And publish from the root of the project.

In your situation publishing **from** `dist` would make things a lot complex and risky. You would have to copy every files that need to be included in the package into `dist`. That includes `.npmignore`, `.gitignore`, `README.md`, `CHANGELOG.md`, `LICENSE`, maybe some documentation and potentially many other files. That's risky because if you add a new file in your project it would be really easy to forget to copy and publish a release without it.

**Comment by appsolutegeek** [comment]
Thanks, yes I am going to return to this way of doing things, I think i changed for all the wrong reasons. Now I am using nestjs - its got way more structure and I am able to abstract a lot of the stuff I am doing right now - into microservices.

So it seems a good time to do it.

Thanks again

**Comment by soymikey** [comment]
That happened to me as well, so i work around with configure package.json file. My configuration: `"bin": {
    "cli": "dist/bin/cli.js"
  }`

**Comment by ryanrosello-og** [comment]
I ran into this problem just now, took me a little while to figure it out.  My problem was trying to be fancy and importing the `package.json` to scrape the name and version of the package.

fixed by removing it for now:

![2023-12-09_20-16-20](https://github.com/semantic-release/npm/assets/50574915/69225c6b-410b-450e-9e87-5ac23b926f06)
