### ISSUE TITLE
Commit yarn.lock

### ISSUE THREAD

**Issue by trollepierre** [semantic-release/npm#154]
Read explanation here ;-)
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by gr2m** [comment]
no thanks

**Comment by trollepierre** [comment]
Maybe I am too curious...
Why?
:p

**Comment by gr2m** [comment]
We discussed adding lockfiles but decided against it. They lock all dependencies, so it’s possible that the library does not work for users while our tests pass, because of an outdated lockfile. The direct dependencies are checked by Greenkeeper in the background, but not the sub dependencies.

We might re-evaluate that decision in future. But if we commit a lock file, it will more likely be `package-lock.json`.

Thanks :)
