### ISSUE TITLE
Security issue with mem < 4.0.0

### ISSUE THREAD

**Issue by mysterycommand** [semantic-release/npm#183]
<img width="757" alt="Screenshot 2019-07-18 22 15 09" src="https://user-images.githubusercontent.com/810398/61504488-89530f80-a9a9-11e9-98ac-d94557ba03db.png">

Just got this on a project of mine that uses `@semantic-release/npm` and it looks like `mem@^1.1.0` is used by `os-locale@^2.0.0` which is used by `yargs@^11.0.0` which is used by `libnpx@^10.2.0` which is used by `npm@^6.8.0` … which is a bummer because `libnpx` appears to have been archived over a year ago. I don't see a security issue on any of these other intermediary projects. I guess just raising it here so that it's on your radar.

**Comment by gr2m** [comment]
I don’t think this vulnerability can be exploited with semantic-release, you should be safe.

**Comment by pvdlg** [comment]
There is nothing we can do here. The problem is that `npm` use an outdated dependency. Please open an issue with `npm`.

**Comment by jessestuart** [comment]
@pvdlg Why not simply upgrade the version of `npm` in `package.json`? It's currently pinned at `^6.8.0', and without a `yarn.lock` file (why _is_ that [excluded](https://github.com/semantic-release/npm/blob/fca8c399c5ad26c597409bd2c3b42f4471c6ad28/.gitignore#L131), btw?), npm/yarn won't resolve newer versions even if semantic versioning flags (`^`, `~`) are specified.

At the very least, we should be able to bump `npm` to the current latest (`6.10.3` at the moment), which would resolve this issue. Or is there any reason for holding that dependency back?

**Comment by pvdlg** [comment]
> It's currently pinned at ^6.8.0, and without a yarn.lock file (why is that excluded, btw?), npm/yarn won't resolve newer versions even if semantic versioning flags (^, ~) are specified.

That's not how lockfiles works....

1/ As indicated by their name they lock dependency version. That mean they prevent to install the latest version even if the dependency definition allows it. That's the exact opposite of what you said.

2/ Lockfiles are not published. So whether we have a lockfile or not that has no impact on you. When you do `npm install semantic-release` you will get all the latests version of the dependency tree, unless you have a lockfile that specifies otherwise.

So if you don't get the latest version of the npm when are doing `npm install semantic-release` it because you have a lockfile that locks to an outdated version.
If you want your project to use the latests version of dependencies (and dependencies of dependencies, etc...) then do not use a lockfile or update it regularly.

**Comment by mysterycommand** [comment]
Unfortunately @pvdlg it's not quite as "do not use a lockfile or update it regularly". In this case running `yarn upgrade` does indeed bump the resolved npm version to 6.10.3 but it still:

- depends on `"libnpx@^10.2.0"` (which resolves to `10.2.0` … and is archived like I mentioned)
  - which depends on `"yargs@^11.0.0"` (which resolves to `11.1.0`)
    - which depends on `"os-locale@^2.0.0"` (which resolves to `2.1.0`)
      - which depends on `"mem@^1.1.0"` (which resolves to `1.1.0`)

… anyway, my point wasn't really to suggest that you fix it. More just to put it on your radar in case it wasn't. I don't even know if there's an issue with how it's actually used, the GitHub security alert feature is new and seems to be a little over paranoid in some cases (which is I guess better than the alternative). WONTFIX, or INVALID is a fine resolution to this and I will go create an issue with npm if one doesn't already exist.

**Comment by mysterycommand** [comment]
… and, for the record, here it is: https://npm.community/t/transitive-vulnerability-yargs-13-3-0/9111

**Comment by pvdlg** [comment]
I'm not sure doing a `yarn upgrade` will upgrade sub-dependencies, sub-sub-dependencies etc...

To be sure to use the last version of each dependency the safest is to delete the lockfile and do `yarn install`.

It's possible the one of the dependency in the chain is too restrictive and prevent to get all the last 
versions. Probably `libnpx` should upgrade to `yargs` `^13.0.0`.

In any case there is nothing we can do here. If the problem was in a fringe and unmaintained library then we would consider removing it from our dependencies. But in that case the problem is with npm...we can't really do anything without it...

**Comment by mysterycommand** [comment]
Just for clarity/reference, `yarn upgrade` will re-resolve all dependencies (including transitive ones) and update the resolved version number and content hash in the `yarn.lock` file.

Removing the lock file and re-running `yarn install` should (I think) be effectively the same as running `yarn upgrade`.

It is exactly the case that `libnpx` is the real culprit here, but as mentioned, the project is archived on GitHub (and thus has no `/issues` page) … I don't see a place or person on that project where or to whom one might report bugs.

I 100% agree there's nothing to be done here (in this project/repo). I would humbly suggest that anyone following this issue go vote on the npm issue [linked above](https://github.com/semantic-release/npm/issues/183#issuecomment-519291673) and see if we can get the npm team to fix it.

**Comment by MitchBred** [comment]
yarn upgrade mem@^4.0.0

**Comment by gabrielf7** [comment]
> atualização de fios mem@^4.0.0

how do i install mem? should i install global or in the project folder?
