### ISSUE TITLE
Possible to generate tar file during dry-run?

### ISSUE THREAD

**Issue by darewreck54** [semantic-release/npm#191]
is it possible to produce the artifacts (tar) files in a step that the dry-run will execute?  

In my use case, I have a custom ci solution which decouples the build and deployment stage.  Ideally, it would be nice if I could just semantic release can generate the artifacts (next version, change log, tag it wants to create, the tar file) without actually doing any write operations.  

The dry-run kind of does this, but it doesn't call the prepare stage which is the stage that this plugin uses to generate the tar files.

Wonder if I could get some advice on this.

Thanks,
Derek

**Comment by pvdlg** [comment]
This is something we purposefully do not want to. The reason is we want to guarantee consistency and accuracy of releases. In other we want to determine the version, create the changelog, create the tag and publish in the same process, so we can guarantee all those match.

We don't want to end up in a situation were a version is tagged on a certain commit, but the tar published has been built with a different version of the codebase.

If you don't want to publish to npm with semantic-release you can use the [`npmPublish` option](https://github.com/semantic-release/npm#options) to skip it. Then you can later publish the tar by yourself. 
However I would advise against doing so as you open the door to inconsistencies as I mention above.

**Comment by dominykas** [comment]
> If you don't want to publish to npm with semantic-release you can use the npmPublish option to skip it. Then you can later publish the tar by yourself.

You can also publish the tar to GH releases - I've played around with a similar setup in the past: https://github.com/dominykas/allow-scripts/blob/53178f75461651c2e27dbaf455304c57144dc36c/package.json#L41-L45

The beauty of this is that you can later `npm publish [URL for the tarball]` and it will just do the right thing, i.e. your assets are generated during the build phase and your "deployment" phase can promote these assets into "production".
