### ISSUE TITLE
Publishing to multiple registries

### ISSUE THREAD

**Issue by limonte** [semantic-release/npm#194]
GitHub Package Registry is in public beta stage now :tada: :tada: :tada: 

Which means that developers will want to publish their npm packages to both npm and GitHub registries.

Is it possible to configure `semantic-release` so it'll publish to multiple registries at the same time?

**Comment by gr2m** [comment]
It should now. I tried a while ago and the only blocker was that GPR created tags & releases when publishing a package, that behavior has recently been removed so no conflict errors should occur. All you'd need to do is set the different registry URL and set `NPM_TOKEN` to `GITHUB_TOKEN` in your action. Can you give it a try? Would love to know myself

**Comment by limonte** [comment]
Thank you @gr2m for the feedback!

> All you'd need to do is set the different registry URL and set NPM_TOKEN to GITHUB_TOKEN in your action. 

Could you please be more specific on how can I set the different registry URL?

**Comment by gr2m** [comment]
It came up in the discussion here:
https://github.com/semantic-release/npm/pull/161

I think that the GitHub registry now also works as a proxy for npm's registry, I don't know if that means that it will publish to both or only fallback to the latter on install

**Comment by pvdlg** [comment]
I don't think publishing to two different registry is a good idea. It just create an opportunity for inconsistencies.

As the GitHub Registry is a proxy to the npm one, you can publish to the npm registry and your package is going to be available to users using the GitHub one.

If you publish to the GitHub one, I guess your package will be accessible only to the GitHub registry users.

**Comment by gr2m** [comment]
> As the GitHub Registry is a proxy to the npm one, you can publish to the npm registry and your package is going to be available to users using the GitHub one.

That's a good point, GitHub kinda solved to need to publish to two registries for a transitional time.

Does that resolve your problem Limon?

**Comment by pvdlg** [comment]
Closing as no response provieded

**Comment by lifeiscontent** [comment]
@pvdlg it seems given the docs on setup-node github action that you should just set the NPM_TOKEN to what the GITHUB_TOKEN should be, I've done this but semantic release seems to error.

https://github.com/actions/setup-node

https://github.com/lifeiscontent/isomorphic-querystring/blob/master/.github/workflows/ci.yml

can we update semantic release to accommodate what setup-node does?

**Comment by rafegoldberg** [comment]
@lifeiscontent setting the `NPM_TOKEN` env variable has worked for me in various workflows before:

```yml
jobs:
  release:
    steps:
      - name: Build and publish release.
        run: npx semantic-release
        env:
          GH_TOKEN: secrets.GITHUB_TOKEN
          NPM_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
```

**Comment by jhnns** [comment]
While I agree that cross-publishing to multiple registries is not ideal, it may be the only solution if you have a private package on Github under `@your-scope` and a public package on NPM under `@your-scope`. In that case, [Github's proxy approach](https://github.blog/news-insights/product-news/proxying-packages-with-github-package-registry-and-other-updates/) won't work (as described in [this Gist](https://gist.github.com/azu/31530916cbce0fd2fc1f4d8f6cf0fae1)).

I was using https://github.com/amanda-mitchell/semantic-release-npm-multiple for publishing to multiple registries but they seem to have troubles to [update the npm plugin since semantic-release switched to ESM](https://github.com/amanda-mitchell/semantic-release-npm-multiple/pull/235).

If you still want to cross-publish your package, you can use [@semantic-release/exec](https://github.com/semantic-release/exec). This is my config for the Github registry:

```json
[
  "@semantic-release/exec",
  {
    "verifyConditionsCmd": "echo //npm.pkg.github.com/:_authToken=${process.env.GITHUB_TOKEN} > temp.npmrc && npm whoami --userconfig temp.npmrc --registry https://npm.pkg.github.com/",
    "publishCmd": "npm publish --userconfig temp.npmrc --tag ${nextRelease.channel} --registry https://npm.pkg.github.com/ --no-git-tag-version",
    "successCmd": "rm temp.npmrc",
    "failCmd": "rm temp.npmrc"
  }
]
```
