### ISSUE TITLE
Fail with 401 Unauthorized but publish package

### ISSUE THREAD

**Issue by wirths** [semantic-release/npm#203]
Publish npm package with GH actions and NPM_TOKEN

## Current behaviour
The plugin publishes the package but fails additionally with 401 Unauthorized as in 'Run npm publish'
https://github.com/zwimlo/gatsby-source-zwimlo/runs/261897164
Beside the failing workflow there seems to be no impact.

## Expected behaviour
Publish without an error.

## Environment
- Github Actions
- semantic-release 16.0.0-beta.26 with  @semantic-release/npm ^5.2.0

Result:
1. Published NPM package
2. Failed GH actions worklflow

**Comment by pvdlg** [comment]
So you run semantic-release first (https://github.com/zwimlo/gatsby-source-zwimlo/runs/261896039) and it works as expected, and then in a second action (https://github.com/zwimlo/gatsby-source-zwimlo/runs/261897164) you call npm publish and it fails...

I don't know why you try to publish again by using this second action...that won't work because semantic-release already publish your package to npm.

Closing as semantic-release works as expected.
