### ISSUE TITLE
Add an option to disable npm token verification.

### ISSUE THREAD

**Issue by jkroepke** [semantic-release/npm#283]
Follow up: https://github.com/semantic-release/npm/issues/277

Please add an option to disable npm token verification. 

This is required for 3rd party Registries that doesnt support the whoami endpoint. Looking at https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md
the whoami endpoint is not a requiered endpoint. 

This means npm whoami is allowed to fail on valid npm registires.

For example the gitlab npm package registry doesnt support whoami.

**Comment by travi** [comment]
are you running into a specific problem with this other than for automation tokens with the default registry? since the npm team has already confirmed that they will enable access for an automation token, i dont expect that we will add an option only for that temporary use case.

the `whoami` check is currently only executed for the default registry because not all of the alternatives support it: https://github.com/semantic-release/npm/blob/493fbad4e2bff62603854a49c670bc70ec895fb7/lib/verify-auth.js#L19

that means that an option shouldnt be needed for those registries either. there are some that _do_ support it that are not being checked, like the github package registry. so, if anything, there are some that could be _added_ at some point.

**Comment by jkroepke** [comment]
Thanks! this helps me.
