### ISSUE TITLE
Version number updated in package.json and package-lock.json instead of package.json in pkgRoot

### ISSUE THREAD

**Issue by pterblgh** [semantic-release/npm#64]
### Versions

```
semantic-release: 15.1.7
@semantic-release/npm: 3.2.4
```

### Configuration

```json
"release": {
    "noCi": true,
    "tagFormat": "${version}",
    "publish": [
      {
        "path": "@semantic-release/npm",
        "pkgRoot": "dist"
      }
    ]
  }
```

### Description

I have an [Angular repository](https://github.com/pterblgh/ngx-officeuifabric) where I would like to use semantic-release to maintain the version number of the library. However I have not succeeded using this package, yet. My build system compiles the source code to the `./dist` folder, which is the code that needs to be published.

As the [documentation declares](https://github.com/semantic-release/npm#options), the script should determine the next version number based on the commit messages and write this version number to the `package.json` in the provided `pkgRoot` folder.

However, unexpectedly, at the end of the release process - currently I'm trying to release from my computer not from CI to have a better debugging experience - the version number of the `package.json` in the `dist` folder remains untouched and the `package.json` and `package-lock.json` files **in the root folder** are updated with the new version number. 

At the end of a process like this, I am ended up with a situation where I have a "successfully" released version on GitHub and an NPM release with an incorrect version number.

I am really happy to share more data about my issue, but I feel lost in this situation.

**Comment by pterblgh** [comment]
Thank you @pvdlg, this tip solved my issue. 

This may be documented somewhere in the docs and I was the one who could not find it, but for a beginner (I've got familiar with semantic-release just today) like me it was totally unclear that steps have "side effects" in configuration setup.

Thank you again!

**Comment by pvdlg** [comment]
The way plugin option works is explained here: https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/plugins.html#configuration

Not sure if it's really clear, but I don't know how to improve. Feel free to propose improvements.

**Comment by EvanCarroll** [comment]
@pvdlg well, one question I have is that in order to build into `dist/` you have to run `ng build`. I assume this is done before semantic release is run. If you do this, how do you bump the version that was produced in `dist` and the version that is in the source? That's what I was trying to do:

1. run `ng build` to populate dist
2. run `semantic-release` to bump the version number in `dist`.
3. [run a postpublish script](https://semantic-release.gitbook.io/semantic-release/support/faq) to sync the bumped version back to the source.
4. run semantic-release/git to push that back to the repo.

Or is there another method of doing this....

From what I can see, even if I could have a different pkgroot for bumping the version number and publishing the package, it wouldn't work: what I really need is for the version number to be set in dist and the source, before publication.
