### ISSUE TITLE
Package version update changes code styling

### ISSUE THREAD

**Issue by byCedric** [semantic-release/npm#70]
First of all, thanks for creating these tools. I recently started using it for some of my projects, and I love it. Unfortunately I saw something I did not like, it changes the code styling when you use an other style instead of 2 spaces. Personally, I think that [commits like this one](https://github.com/byCedric/semantic-release-expo/commit/26a1916fdbd2acb6f8735f78988f1c49b86b272a) can and should be avoided. Luckily there is a package out there that can detect a used indentation, [detect-indent](https://github.com/sindresorhus/detect-indent). 

I also created a plugin for semantic releases to manage Expo release updates. In this library I used detect indent to use the original indentation of the file instead of a hardcoded version, [you can see this happening here](https://github.com/byCedric/semantic-release-expo/blob/master/src/expo.ts#L34). If you want I can create a PR to create a first draft of an implementation.

Cheers,
Cedric

**Comment by gr2m** [comment]
Hi @byCedric, thanks for the kind words!

Just so I understand correctly, this issue is about the update of the package.json file in this line?

https://github.com/semantic-release/npm/blob/master/lib/update-package-version.js#L10

I think we can fix that to keep the indentation style. E.g. we could use https://www.npmjs.com/package/json-in-place, that’s what Greenkeeper is using to update the package.json files in its pull requests. Wanna send a pull request for that? Maybe add a test that the indentation style is indeed not changed so we don’t break it by accident in future

**Comment by byCedric** [comment]
Hi Gregor, yes exactly! When writing to either the `package.json`, `package-lock.json` or `shrinkwrap.json` the code styling will be reset to two spaces indentation. I'll create a PR with the `json-in-place` package now!

**Comment by pvdlg** [comment]
Oh sorry I was working on that for the last hour or so and I already published a fix: #71.

I'm using `detect-indent` and `detect-newline` similarly to what npm does: https://github.com/npm/npm/blob/latest/lib/install/save.js#L54

**Comment by byCedric** [comment]
Haha, no worries, I was just starting. Thanks for giving a notice!
